import { IRField, IRSchema } from '../../core/types.js';

export class PythonBlock {
  /**
   * Convert field to Python / Pydantic type annotation
   */
  private static toPythonType(field: IRField): string {
    let pyType = 'str';

    switch (field.type) {
      case 'number':
        pyType = 'float';
        break;
      case 'boolean':
        pyType = 'bool';
        break;
      case 'array':
        let itemPy = 'str';
        if (field.itemType === 'number') itemPy = 'float';
        else if (field.itemType === 'boolean') itemPy = 'bool';
        else if (field.itemType === 'object') itemPy = 'dict[str, Any]';
        pyType = `list[${itemPy}]`;
        break;
      case 'object':
        pyType = 'dict[str, Any]';
        break;
      case 'enum':
      case 'string':
      default:
        pyType = 'str';
        break;
    }

    if (!field.required) {
      pyType = `Optional[${pyType}] = None`;
    }

    return pyType;
  }

  /**
   * Generate Pydantic v2 Model and FastAPI route stub
   */
  public static generate(schema: IRSchema): string {
    const fields = Object.values(schema.fields);
    const pyFields = fields
      .map((field) => `    ${field.name}: ${this.toPythonType(field)}`)
      .join('\n');

    return `"""
AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
Route: ${schema.route} (v${schema.version})
Frozen At: ${schema.frozenAt || new Date().toISOString()}

DO NOT EDIT MANUALLY - Code Block: ast_python
"""

from typing import Any, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/${schema.route}", tags=["${schema.route}"])


class ${schema.name}(BaseModel):
${pyFields}


@router.post("/", response_model=dict[str, Any])
async def handle_${schema.route.replace(/[^a-zA-Z0-9]/g, '_')}(payload: ${schema.name}):
    """
    Fast-path endpoint generated from JIT Protocol Synthesis
    0 AI Latency, native Pydantic validation
    """
    return {
        "status": "success",
        "route": "${schema.route}",
        "version": ${schema.version},
        "data": payload.model_dump(),
    }
`;
  }
}
