import { IRField, IRSchema } from '../../core/types.js';

export class GolangBlock {
  /**
   * Convert field to Go type
   */
  private static toGoType(field: IRField): string {
    switch (field.type) {
      case 'number':
        return 'float64';
      case 'boolean':
        return 'bool';
      case 'array':
        if (field.itemType === 'number') return '[]float64';
        if (field.itemType === 'boolean') return '[]bool';
        if (field.itemType === 'object') return '[]map[string]interface{}';
        return '[]string';
      case 'object':
        return 'map[string]interface{}';
      case 'enum':
      case 'string':
      default:
        return 'string';
    }
  }

  /**
   * Convert field to Proto3 type
   */
  private static toProtoType(field: IRField): string {
    switch (field.type) {
      case 'number':
        return 'double';
      case 'boolean':
        return 'bool';
      case 'array':
        let itemType = 'string';
        if (field.itemType === 'number') itemType = 'double';
        else if (field.itemType === 'boolean') itemType = 'bool';
        return `repeated ${itemType}`;
      case 'object':
        return 'string'; // Serialized or map
      case 'enum':
      case 'string':
      default:
        return 'string';
    }
  }

  private static toPascalCase(str: string): string {
    return str
      .split(/[_-]/)
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join('');
  }

  /**
   * Generate Protobuf 3 (.proto) definition
   */
  public static generateProto(schema: IRSchema): string {
    const fields = Object.values(schema.fields);
    const protoFields = fields
      .map((field, idx) => `  ${this.toProtoType(field)} ${field.name} = ${idx + 1};`)
      .join('\n');

    return `// AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
// Route: ${schema.route} (v${schema.version})
// Frozen At: ${schema.frozenAt || new Date().toISOString()}

syntax = "proto3";

package jit.v${schema.version};

option go_package = "jit/gen/v${schema.version};jitv${schema.version}";

message ${schema.name} {
${protoFields}
}
`;
  }

  /**
   * Generate Go Struct definition
   */
  public static generateGoStruct(schema: IRSchema): string {
    const fields = Object.values(schema.fields);
    const structFields = fields
      .map((field) => {
        const fieldName = this.toPascalCase(field.name);
        const goType = this.toGoType(field);
        return `\t${fieldName} ${goType} \`json:"${field.name}${
          field.required ? '' : ',omitempty'
        }" protobuf:"bytes,json=${field.name}"\``;
      })
      .join('\n');

    return `// AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
// Route: ${schema.route} (v${schema.version})
// Frozen At: ${schema.frozenAt || new Date().toISOString()}

package models

type ${schema.name} struct {
${structFields}
}
`;
  }
}
