import json
import os
from typing import Any, Dict, Optional
from .types import IRField, IRSchema


class CodegenEngine:
    """
    Compiles IRSchema into multi-language contracts (TypeScript, Go, Python, IR JSON).
    """

    def __init__(self, output_dir: Optional[str] = None):
        self.output_dir = output_dir or os.path.abspath("generated")

    def _ensure_dirs(self) -> None:
        for sub in ["typescript", "golang", "python", "schemas"]:
            os.makedirs(os.path.join(self.output_dir, sub), exist_ok=True)

    def generate_python(self, schema: IRSchema) -> str:
        fields_code = []
        for f in schema.fields.values():
            py_t = "str"
            if f.type == "number":
                py_t = "float"
            elif f.type == "boolean":
                py_t = "bool"
            elif f.type == "array":
                item_t = "float" if f.item_type == "number" else ("bool" if f.item_type == "boolean" else "str")
                py_t = f"list[{item_t}]"
            elif f.type == "object":
                py_t = "dict[str, Any]"

            if not f.required:
                py_t = f"Optional[{py_t}] = None"

            fields_code.append(f"    {f.name}: {py_t}")

        return f'''"""
AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK (Python)
Route: {schema.route} (v{schema.version})
Frozen At: {schema.frozen_at}
"""

from typing import Any, Optional
from pydantic import BaseModel
from fastapi import APIRouter

router = APIRouter(prefix="/{schema.route}", tags=["{schema.route}"])


class {schema.name}(BaseModel):
{chr(10).join(fields_code)}


@router.post("/", response_model=dict[str, Any])
async def handle_{schema.route.replace("-", "_")}(payload: {schema.name}):
    return {{
        "status": "success",
        "route": "{schema.route}",
        "version": {schema.version},
        "data": payload.model_dump(),
    }}
'''

    def generate_typescript(self, schema: IRSchema) -> str:
        fields_code = []
        for f in schema.fields.values():
            z_t = "z.string()"
            if f.type == "number":
                z_t = "z.number()"
            elif f.type == "boolean":
                z_t = "z.boolean()"
            elif f.type == "array":
                item_z = "z.number()" if f.item_type == "number" else ("z.boolean()" if f.item_type == "boolean" else "z.string()")
                z_t = f"z.array({item_z})"
            elif f.type == "object":
                z_t = "z.record(z.unknown())"

            if not f.required:
                z_t += ".optional()"
            fields_code.append(f"  {f.name}: {z_t},")

        return f'''/**
 * AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK (Python Host)
 * Route: {schema.route} (v{schema.version})
 */

import {{ z }} from 'zod';

export const {schema.name}Schema = z.object({{
{chr(10).join(fields_code)}
}});

export type {schema.name} = z.infer<typeof {schema.name}Schema>;
'''

    def generate_golang(self, schema: IRSchema) -> Dict[str, str]:
        # 1. Proto3
        proto_fields = []
        for idx, f in enumerate(schema.fields.values(), 1):
            pr_t = "string"
            if f.type == "number":
                pr_t = "double"
            elif f.type == "boolean":
                pr_t = "bool"
            elif f.type == "array":
                pr_t = f"repeated {'double' if f.item_type == 'number' else 'string'}"
            proto_fields.append(f"  {pr_t} {f.name} = {idx};")

        proto = f'''// AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
syntax = "proto3";

package jit.v{schema.version};

option go_package = "jit/gen/v{schema.version};jitv{schema.version}";

message {schema.name} {{
{chr(10).join(proto_fields)}
}}
'''
        # 2. Go Struct
        go_fields = []
        for f in schema.fields.values():
            field_name = "".join(part.capitalize() for part in f.name.split("_"))
            go_t = "string"
            if f.type == "number":
                go_t = "float64"
            elif f.type == "boolean":
                go_t = "bool"
            elif f.type == "array":
                go_t = "[]float64" if f.item_type == "number" else "[]string"
            elif f.type == "object":
                go_t = "map[string]interface{}"
            go_fields.append(f'\t{field_name} {go_t} `json:"{f.name}"`')

        go_struct = f'''// AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
package models

type {schema.name} struct {{
{chr(10).join(go_fields)}
}}
'''
        return {"proto": proto, "golang": go_struct}

    def compile(self, schema: IRSchema) -> Dict[str, Any]:
        self._ensure_dirs()
        base = schema.route.replace("-", "_")

        py_code = self.generate_python(schema)
        py_path = os.path.join(self.output_dir, "python", f"{base}.py")
        with open(py_path, "w", encoding="utf-8") as f:
            f.write(py_code)

        ts_code = self.generate_typescript(schema)
        ts_path = os.path.join(self.output_dir, "typescript", f"{base}.ts")
        with open(ts_path, "w", encoding="utf-8") as f:
            f.write(ts_code)

        go_res = self.generate_golang(schema)
        proto_path = os.path.join(self.output_dir, "golang", f"{base}.proto")
        with open(proto_path, "w", encoding="utf-8") as f:
            f.write(go_res["proto"])

        go_path = os.path.join(self.output_dir, "golang", f"{base}.go")
        with open(go_path, "w", encoding="utf-8") as f:
            f.write(go_res["golang"])

        ir_dict = {
            "name": schema.name,
            "version": schema.version,
            "route": schema.route,
            "fields": {k: v.__dict__ for k, v in schema.fields.items()},
            "frozen_at": schema.frozen_at,
        }
        ir_path = os.path.join(self.output_dir, "schemas", f"{base}.json")
        with open(ir_path, "w", encoding="utf-8") as f:
            json.dump(ir_dict, f, indent=2)

        return {
            "schema": schema,
            "files": {
                "python": py_path,
                "typescript": ts_path,
                "proto": proto_path,
                "golang": go_path,
                "ir_json": ir_path,
            },
        }
