import { IRField, IRSchema } from '../../core/types.js';

export class TypeScriptBlock {
  /**
   * Map IRField to Zod schema code representation
   */
  private static fieldToZod(field: IRField): string {
    let zodType = 'z.string()';

    switch (field.type) {
      case 'number':
        zodType = 'z.number()';
        break;
      case 'boolean':
        zodType = 'z.boolean()';
        break;
      case 'array':
        let itemZod = 'z.string()';
        if (field.itemType === 'number') itemZod = 'z.number()';
        else if (field.itemType === 'boolean') itemZod = 'z.boolean()';
        else if (field.itemType === 'object') itemZod = 'z.record(z.unknown())';
        zodType = `z.array(${itemZod})`;
        break;
      case 'object':
        if (field.properties) {
          const subFields = Object.values(field.properties)
            .map((sub) => `    ${sub.name}: ${this.fieldToZod(sub)}`)
            .join(',\n');
          zodType = `z.object({\n${subFields}\n  })`;
        } else {
          zodType = 'z.record(z.unknown())';
        }
        break;
      case 'enum':
        if (field.enumValues && field.enumValues.length > 0) {
          const enumItems = field.enumValues.map((e) => `'${e}'`).join(', ');
          zodType = `z.enum([${enumItems}])`;
        } else {
          zodType = 'z.string()';
        }
        break;
      case 'string':
      default:
        zodType = 'z.string()';
        break;
    }

    if (!field.required) {
      zodType += '.optional()';
    }

    return zodType;
  }

  /**
   * Generate TypeScript Zod schema & types from IRSchema (Request + Typed Response)
   */
  public static generate(schema: IRSchema): string {
    const schemaConstName = `${schema.name}Schema`;
    const typeName = schema.name;
    const baseName = schema.name.replace(/Request$/, '');
    const responseSchemaConstName = `${baseName}ResponseSchema`;
    const responseTypeName = `${baseName}Response`;

    const fieldsCode = Object.values(schema.fields)
      .map((field) => `  ${field.name}: ${this.fieldToZod(field)},`)
      .join('\n');

    let responseCode = '';
    if (schema.responseFields && Object.keys(schema.responseFields).length > 0) {
      const resFieldsCode = Object.values(schema.responseFields)
        .map((field) => `  ${field.name}: ${this.fieldToZod(field)},`)
        .join('\n');

      responseCode = `
export const ${responseSchemaConstName} = z.object({
${resFieldsCode}
});

export type ${responseTypeName} = z.infer<typeof ${responseSchemaConstName}>;
`;
    }

    return `/**
 * AUTO-GENERATED BY JIT PROTOCOL SYNTHESIS FRAMEWORK
 * Route: ${schema.route} (v${schema.version})
 * Frozen At: ${schema.frozenAt || new Date().toISOString()}
 * 
 * DO NOT EDIT MANUALLY - Code Block: ast_typescript
 */

import { z } from 'zod';

export const ${schemaConstName} = z.object({
${fieldsCode}
});

export type ${typeName} = z.infer<typeof ${schemaConstName}>;
${responseCode}
/**
 * Fast-path validator (0 AI latency, 100% type-safe)
 */
export function validate${typeName}(data: unknown): {
  success: boolean;
  data?: ${typeName};
  error?: string;
} {
  const result = ${schemaConstName}.safeParse(data);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    error: result.error.errors.map((e) => \`\${e.path.join('.')}: \${e.message}\`).join('; '),
  };
}
`;
  }
}
